### ISSUE TITLE
[G006] Low-Fi Sketches

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#20]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G006_Low_Fi_Sketches.md

**Comment by chocoelho** [comment]
Para visualizar -> [Low-Fi Sketches](https://github.com/ije-equipe2/game/wiki/LowFi-Sketches)

**Comment by edsomjr** [comment]
Lembre-se de continuar atualizando estas artes a medida que foram sendo produzidas.
