### ISSUE TITLE
[D011] Sistema de Pontuação

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#26]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D011_Sistema_de_Pontuacao.md

**Comment by Makrau** [comment]
Não se aplica. O único parâmetro de "pontuação" existente seria a própria vitória.
Como o jogo não se preocupa com "contas" de jogadores para manter um histórico ou algo do tipo, um sistema de pontuação não é aplicável.
