### ISSUE TITLE
[D012] Economia

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#27]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D012_Economia.md

**Comment by Makrau** [comment]
Não se aplica. No nosso jogo não é possível comprar itens e nem existe nenhuma moeda ou sistema que envolva algo relacionado a comércio.

**Comment by edsomjr** [comment]
Uma dúvida, antes de fechar a issue: existe algum item colecionável nas arenas, que podem ser acumulados para trocar por itens, ou mesmo para juntar experiência e comprar habilidades? Se a resposta for sim, estas características devem fazer parte desta seção.

**Comment by Makrau** [comment]
A princípio não. Se houvesse um modo single player esse tipo de questão poderia até entrar, mas a equipe entende que para a entrega do trabalho isso aumentaria muito o escopo.
Logo nós não teremos nenhum colecionável ou algo que possa ser comprado/evoluído.
