### ISSUE TITLE
[D014] Veículos

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#29]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D014_Veiculos.md

**Comment by Makrau** [comment]
Professor, no nosso jogo não haverá veículos, pois trata-se de um jogo estilo arena onde não há momentos do jogo onde os personagens caminham pelo mundo ou algo do tipo.

**Comment by edsomjr** [comment]
Uma dúvida: os personagens terão montarias ou algo do tipo? Se sim elas entrariam nesta seção de veículos. Caso contrário poderemos encerrar esta issue.

**Comment by Mattioli** [comment]
Não, Edson, não terão.

**Comment by edsomjr** [comment]
Ok.
