### ISSUE TITLE
[G004] Cronograma

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#5]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/G004_Cronograma.md

**Comment by edsomjr** [comment]
Carlos,

dê apenas uma ajeitada na última parte, que ficou com a pontuação/encadeamento de ideias ruim.

**Comment by chocoelho** [comment]
[Cronograma](https://github.com/ije-equipe2/game/wiki/Cronograma), milestone de Preparação pronta, as outras tasks estão sendo colocadas as datas e as pendências.
