### ISSUE TITLE
[P001] Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#6]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/P001_Ambiente_de_Desenvolvimento.md

**Comment by chocoelho** [comment]
@ije-equipe2/programmers

**Comment by Mattioli** [comment]
[Ambiente de Desenvolvimento](https://github.com/ije-equipe2/game/wiki/Ambiente-de-Desenvolvimento)
