### ISSUE TITLE
[D001] Versão Inicial do Documento de Visão

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#7]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D001_Versao_Inicial_do_Documento_de_Visao.md

**Comment by Makrau** [comment]
https://github.com/ije-equipe2/game/wiki/Documento-de-Vis%C3%A3o

**Comment by edsomjr** [comment]
Iago,

o texto está bom e pode ser reaproveitado no GDD. Contudo, na versão final do documento de visão, tente deixar a coisa um pouco mais sintética/resumida, com apelo mais visual.
