### ISSUE TITLE
[D003] Versão Inicial do GDD

### ISSUE THREAD

**Issue by edsomjr** [ije-equipe2/game#9]
Detalhes em https://github.com/fgagamedev/IJE/blob/master/tasks/D003_Versao_Inicial_do_GDD.md

**Comment by msfernandes** [comment]
@edsomjr 
https://github.com/ije-equipe2/game/wiki/Game-Design-Document

**Comment by edsomjr** [comment]
@msfernandes Falta contemplar os itens de 1 a 3 da tarefa e, em relação aos controles, é preciso montar uma imagem com os esquemáticos para os controles e também para a jogabilidade em teclado/mouse.

**Comment by Makrau** [comment]
Atualizado: https://github.com/ije-equipe2/game/wiki/Game-Design-Document
